### ISSUE TITLE
don't need this pattern

### ISSUE THREAD

**Issue by aric87** [jayzamazing/Shopping-List-App#7]
here:https://github.com/jayzamazing/Shopping-List-App/blob/master/js/index.js#L28 and other places, you create an anonymous function that calls a named function. Instead, you can pass the named function. This will work identically to the way you have it now, because the event is still going to be passed in.

```
$('.listNames').on('mousedown', '.delete',deleteList);
```

**Comment by jayzamazing** [comment]
https://github.com/jayzamazing/Shopping-List-App/pull/14 fixes this issue.

**Comment by jayzamazing** [comment]
Removing this pattern broke delete on the lists, had to change both lines back to fix delete.

**Comment by jayzamazing** [comment]
https://github.com/jayzamazing/Shopping-List-App/pull/14
